GET https://<9z1x9qfr>.api.sanity.io/v2023-02-05/data/query/<production>

###

GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "expressuser1",
    "password": "password"
}

###

POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "tfire09",
    "psw": "prime100"
}